### ISSUE TITLE
Add NACE code to organization

### ISSUE THREAD

**Issue by mariepauline** [Altinn/altinn-register#118]
### Description

In Enhetsregisteret "Næringskode" (NACE code) is stored. It would be nice to have these fields (NACE code and description) on the Organization object.

### Additional Information

Enhetsregisteret: https://data.brreg.no/enhetsregisteret/api/docs/index.html#enheter-oppslag

**Comment by annerisbakk** [comment]
@elwal Kan du sjekke om det egentlig er behov for denne i Altinn 3.0. Usikker på om denne er i bruk i Altinn 2.0.
Har det betydning for migrering av apper?

**Comment by SandGrainOne** [comment]
@rtafj Er det dere som eier register nå, og kan ta saker som dette?

**Comment by ekorra** [comment]
Som @elwal sier finnes det alternativ løsning og vil derfor ikke gjøre noe endringer i forhold til dette før vi går over til nytt enhetsregister
