### ISSUE TITLE
Missing value for UnitType

### ISSUE THREAD

**Issue by SimenRokaas** [Altinn/altinn-register#124]
### Description of the bug

We need to know whether an actor is 'hovedenhet' or 'underenhet' in ER (enhetsregistreret). From https://docs.altinn.studio/nb/app/development/data/prefill/config/#enhetsregisteret it seems that 'UnitType' would be perfect for this, but it does not seem to have any value no matter what actor type is chosen in TT02.

### Steps To Reproduce

1. Go to https://dsb.apps.tt02.altinn.no/dsb/elvirksomhet/
2. Log in as Tenor user 26896599908
3. Select actor, either 'hovedenhet' or 'underenhet'
4. The prefilled field UnitType is shown on first page. It should show if actor is 'hovedenhet' or 'underenhet' but is empty.

**Comment by annerisbakk** [comment]
@lovoll Kan du sjekke om unit type ligger riktig i Altinn 2.0?

**Comment by ekorra** [comment]
Er denne fremdeles gjeldende?

**Comment by annerisbakk** [comment]
Usikker på om denne fremdeles er relevant.
Produksjon i Register basen så er Enhetstype fylt ut for de fleste enheter men vet ikke om dette faktisk hentes ut i API
I Prod er det 3 368 som ikke har enhetstype og resten 4 667 984 har enhetstype.
Det er bare 2 uten enhetstype i TT02 og 748 086 med enhetstype så regner med at det er API som ikke henter ut denne informasjonen
