### ISSUE TITLE
GetOrganization returns org with empty UnitStatus

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-register#85]
### Description of the bug

In the app [brg/rrh-innrapportering](https://altinn.studio/repos/brg/rrh-innrapportering/src/branch/master/App/logic/InstantiationValidator.cs), we are attempting to bar units that are deleted from instansiating the app.

For this we use the IRegister service to fetch the org data and attempt to check their UnitStatus.
But when we do, we don't get a value. That is, we do in local testing, but when printing the UnitStatus in TT02 with an org we know is marked deleted (with UnitStatus "S"), we get nothing.

Logging `$"Unit status is {org.UnitStatus}"` in TT02
Yields the following:
![image](https://user-images.githubusercontent.com/22012997/201094141-8af50fa2-9cdf-440b-8ac2-28dc55fa92b3.png)
When we expected to see "Unit status is S"

### Steps To Reproduce

`Organization org = await _registerService.ER.GetOrganization(orgNo);
print org.UnitStatus`

This prints empty in TT02 when testing with an org that should be deleted and thus should have UnitStatus "S"

### Cause / Resolution 
Bug is due to a missing attribute on the UnitStatus property in the Organization class in SBL Bridge causing the property to be lost during serialization. 

Missing attribute has now been added and fix has been verified. 

Waiting to determine which release of SBL the fix will be included in.

**Comment by SandGrainOne** [comment]
This issue is highly likely originating in Altinn 2 as we use them as unit information source. The value should be available, but for some reason it's lost on the way to Altinn 3 and the App. It's probably an easy fix once we know where the problem starts, but in Altinn 2 we're limited to monthly releases.

**Comment by acn-sbuad** [comment]
https://dev.azure.com/digdir/Altinn/_workitems/edit/62100/

**Comment by acn-sbuad** [comment]
Fix verified in AT24. 
Fix expected to be deployed in TT 14.11.2022 and Production 21.11.2022

**Comment by allinox** [comment]
Fantastic! Brilliant work! 🤩
