### ISSUE TITLE
IPersonLookup.GetPerson returns a person with empty first and middle names

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-register#89]
### Description of the bug

Fetching a person like this: 
`Platform.Register.Models.Person person = await _personLookup.GetPerson(ssn, surname, CancellationToken.None);`
returns a person that I would expect to have data on person.Name, person.LastName, person.FirstName, and person.MiddleName, where the Name is the combination of the other three.
However, in testing in TT02, only the first two of these values are set correctly. Both First- and MiddleName are empty, despite knowing that they have values in the national registry, and despite these values being present in the full name.

### Steps To Reproduce

1. Get a person from IPersonLookup.GetPerson
2. Display name, first name, last name, and middle name
3. Test this in tt02 with a test user (ex. 11107700678 - Daniela Bell, or 67908801293 - From Ledende Jordbær Vegg)
4. Observe that first name and middle name are empty

### Additional Information

Ensure that testing is done with persons from the Tenor data set. The old Register imports are of a lower quality and might be missing data. Alternatively verify that the person have complete data in the Altinn 2 database.

Remember that there are multiple applications in a call chain:
- SblBridge 
- Platform Register
- App Lib

### Threat modeling

This issue is considered a bug on existing functionality. No new threat boundaries or new elements to consider.

**Comment by acn-sbuad** [comment]
Related to: 
- #93

**Comment by elwal** [comment]
Denne haster for Finanstilsynet da de ikke får produksjonssatt KRT-1061 (de trenger også funksjonaliteten i andre skjema)

Fra Finanstilsynet: 
Jeg bruker PersonLookUp-tjenesten til å hente persondata ved å sende inn fødselsnummer og etternavn. Lokalt, når jeg tester appen med testdata, fungerer alt som det skal.
I dag testet jeg applikasjonen i tt02-miljøet ved å bruke Tnor-persondata. Jeg merker at PersonLookUp-tjenesten returnerer null for feltet "FirstName". Jeg har logget ut de forskjellige feltene og sjekket APP-insight. Det ser ut til at personLookup-tjenesten returnerer null for "FirstName" for ulike personer jeg har forsøkt å hente data for.  Det kan hende at det er en mulig feil i kartleggingen mellom Tnor-data og PersonLookup-tjenesten (dette er imidlertid ikke bekreftet da jeg ikke har sett koden).  Dette problemet har blitt rapporter i november-2022.
 
I tillegg får man feilmelding etter 1-3 ganger feil forsøk også usikker når man får tillatelse for ny forsøk etter at man får feilmeldingen.

**Comment by SandGrainOne** [comment]
Vi har med vilje vært litt forsiktig med å angi nøyaktige tall for hvor lenge brukeren må vente før de kan forsøke med ny kombinasjon av personnummer og etternavn. Men så veldig hemmelig er det [ikke](https://github.com/Altinn/altinn-register/blob/main/src/appsettings.json#L4C11-L4C11).

Vi har skrevet litt mer om mekanismen i [dokumentasjonen](https://docs.altinn.studio/app/development/logic/services/) vår.

**Comment by annerisbakk** [comment]
Kommentar fra @HenningNormann
 I prod er det 10237  personer uten fornavn (22 med profil). Det er 18065 uten navn (229 med profil). (Det burde vært <10237 siden navn skal inkludere fornavn).

**Comment by SandGrainOne** [comment]
Fix has been deployed to TT02.
Deploy to production will be done on Tuesday(19.09)
