### ISSUE TITLE
Evaluate and adjust how SblBridge obtains Person and Organisation information

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-register#93]
## Description
It was recently discovered that the `FirstName` property of `Person` is never populated in the call chain currently used by SblBridge. We need to evaluate how SblBridge obtains `Person` and `Organisation` information and ensure that as many properties as possible are being populated correctly.

## Considerations
- We're hopefully able to identify a working call chain (proxy) that SblBridge can consume, but we should be willing to create a new call chain and database procedure if necessary.
- Use multiple data sources (datbases and tables) to populate as much as possible.
- Also evaluate the quality of Person and Organisation data in the database. Ask operations (FA) for help to access TT02 and production when needed. FA might also be able to tell us more about which database and tables that should be used.
- Identify how the rest of SBL obtains the same information if at all.

If we have problems populating all properties of Person, Organisation etc, we must consider making a new version of the Register API with a reduced set of exposed properties. Having many properties never being populated is confusing for app developers.

### Ops requirements
This should not introduce anything new in this regard.

## Acceptance criteria
- Person, Organisation and SI-User lookup returns correctly and completely populated instance objects.

## Specification tasks
- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by acn-sbuad** [comment]
moved to register repo, as the dependency in SBL bridge is related to register functionality.

**Comment by annerisbakk** [comment]
Issues are fixed as they are identified
